# -- PaperMod Theme Options --
# Refer to the theme docs for more details about each of these parameters.
# https://adityatelange.github.io/hugo-PaperMod/
# https://github.com/adityatelange/hugo-PaperMod/wiki/Variables

env = "production"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = false
disableScrollToTop = false

[footer]
  hideCopyright = true
